CREATE TABLE APT_MANGEMENT (
APT_CD INT PRIMARY KEY,
APT_BRAND VARCHAR (200) ,
APT_COMPLEX INT ,
APT_ALL INT 
);

CREATE TABLE HOUES_REGIST (
RG_NO INT PRIMARY KEY,
APT_OWNER VARCHAR (30) ,
PHONE VARCHAR (30) ,
APT_CD INT NOT NULL,
APT_DONG INT ,
APT_HOSU INT,
REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(APT_CD) REFERENCES APT_MANGEMENT(APT_CD)
);

CREATE TABLE APT_ACCESS (
ACCESS_DATE TIMESTAMP PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
CAR_NO VARCHAR (20) NOT NULL,
ACCESS_TYPE VARCHAR (10),
FOREIGN KEY (CAR_NO) REFERENCES CAR_REGIST(CAR_NO)
);

CREATE TABLE CAR_REPORT (
CAR_CD INT PRIMARY KEY ,
CAR_NO VARCHAR (20) NOT NULL,
RG_NO INT NOT NULL,
OWNER VARCHAR (10),
REPORT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (CAR_NO) REFERENCES CAR_REGIST(CAR_NO),
FOREIGN KEY (RG_NO) REFERENCES HOUES_REGIST(RG_NO)
);

CREATE TABLE CAR_REGIST (
CAR_NO VARCHAR (20) PRIMARY KEY,
CAR_TYPE VARCHAR (10) ,
MAKER VARCHAR (10) ,
COLOR VARCHAR (10)
);
