CREATE TABLE APT_MANGEMENT (
APT_CD INT AUTO_INCREMENT PRIMARY KEY COMMENT '아파트 관리코드',
APT_BRAND VARCHAR (200) COMMENT '아파트 브랜드',
APT_COMPLEX INT COMMENT '아파트 단지',
APT_ALL INT COMMENT '총 건물수'
);

CREATE TABLE HOUES_REGIST (
RG_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '세대주 등록번호',
APT_OWNER VARCHAR (30) NOT NULL COMMENT '대표자',
PHONE VARCHAR (30) NOT NULL COMMENT '연락처', 
APT_CD INT NOT NULL COMMENT '아파트 관리번호',
APT_DONG INT NOT NULL COMMENT '아파트 번호(동)',
APT_HOSU INT NOT NULL COMMENT '호수',
REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록날짜',
FOREIGN KEY(APT_CD) REFERENCES APT_MANGEMENT(APT_CD)
);

CREATE TABLE APT_ACCESS (
ACCESS_DATE TIMESTAMP PRIMARY KEY DEFAULT CURRENT_TIMESTAMP COMMENT '출입 기록날짜',
CAR_NO VARCHAR (20) NOT NULL COMMENT '차번호',
ACCESS_TYPE VARCHAR (10) NOT NULL COMMENT '출입타입',
FOREIGN KEY (CAR_NO) REFERENCES CAR_REGIST(CAR_NO)
);

CREATE TABLE CAR_REPORT (
CAR_CD INT AUTO_INCREMENT PRIMARY KEY COMMENT '자동차 신고코드',
CAR_NO VARCHAR (20) NOT NULL COMMENT '차번호',
RG_NO INT NOT NULL COMMENT '세대주 등록번호',
OWNER VARCHAR (10) COMMENT '대표자',
REPORT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '소유 신고날짜',
FOREIGN KEY (CAR_NO) REFERENCES CAR_REGIST(CAR_NO),
FOREIGN KEY (RG_NO) REFERENCES HOUES_REGIST(RG_NO)
);

CREATE TABLE CAR_REGIST (
CAR_NO VARCHAR (20) PRIMARY KEY COMMENT '차번호',
CAR_TYPE VARCHAR (10) COMMENT '차종류',
MAKER VARCHAR (10) COMMENT '제조사',
COLOR VARCHAR (10) COMMENT '색깔',
CAR_REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록날짜'
);